    - uses: actions/checkout@v3
    - uses: yunwei37/OpenAI-Continuous-Translator@master
      with:
          git_repo_url: https://github.com/Dastrateam/dastra-doc-n
          api_key: ${{ secrets.OPENAI_API_KEY }}
